IF NOT EXIST "OLD" (MKDIR OLD)
IF NOT EXIST "NEW" (MKDIR NEW)

type NUL > NEW\ALTER_TABLE_ENT_TR_2
type NUL > NEW\ALTER_TABLE_ENT_TR_9
type NUL > NEW\ALTER_TABLE_ENT_TR_17
type NUL > NEW\ALTER_TABLE_ENT_TR_27
type NUL > NEW\ALTER_TABLE_ENT_TR_37
type NUL > NEW\CREATE_TABLE_ENT_TR_81
type NUL > NEW\CREATE_TABLE_ENT_TR_82
type NUL > NEW\CREATE_TABLE_ENT_TR_83
type NUL > NEW\CREATE_TABLE_ENT_TR_84
type NUL > NEW\CREATE_TABLE_ENT_TR_85
type NUL > NEW\CREATE_TABLE_ENT_TR_86
type NUL > NEW\CREATE_TABLE_ENT_TR_87
type NUL > NEW\CREATE_TABLE_ENT_TR_88
type NUL > NEW\CREATE_TABLE_ENT_TR_89
type NUL > NEW\CREATE_TABLE_ENT_TR_90
type NUL > NEW\CREATE_TABLE_ENT_TR_60
type NUL > ALTER_TABLE_ENT_TR_17
type NUL > ALTER_TABLE_ENT_TR_17
type NUL > ALTER_TABLE_ENT_TR_17
